USE [master]
GO
/****** Object:  Database [Ingreso]    Script Date: 5/4/2020 2:01:14 p. m. ******/
CREATE DATABASE [Ingreso]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ingreso', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\Ingreso.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ingreso_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\Ingreso_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Ingreso] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ingreso].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ingreso] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ingreso] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ingreso] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ingreso] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ingreso] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ingreso] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ingreso] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ingreso] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ingreso] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ingreso] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ingreso] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ingreso] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ingreso] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ingreso] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ingreso] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ingreso] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ingreso] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ingreso] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ingreso] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ingreso] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ingreso] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ingreso] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ingreso] SET RECOVERY FULL 
GO
ALTER DATABASE [Ingreso] SET  MULTI_USER 
GO
ALTER DATABASE [Ingreso] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ingreso] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ingreso] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ingreso] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ingreso] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ingreso', N'ON'
GO
ALTER DATABASE [Ingreso] SET QUERY_STORE = OFF
GO
USE [Ingreso]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 5/4/2020 2:01:14 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[idUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [varchar](50) NOT NULL,
	[Clave] [varchar](50) NOT NULL,
	[Estado] [int] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[idUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Ingreso] SET  READ_WRITE 
GO
